### ISSUE TITLE
NGINX issue or may need help.

### ISSUE THREAD

**Issue by configari** [Southclaws/storyden#321] opened 2024-12-19 18:44 UTC
I'm encountering an issue where the API works fine with the nginx configuration, but the web service throws a 502 Bad Gateway error, even though the web service is accessible on the host. Here's a breakdown of my setup:

1. **docker-compose.yml** file:
```yaml
version: '3.8'

services:
  storyden:
    image: ghcr.io/southclaws/storyden
    container_name: storyden
    environment:
      - PUBLIC_API_ADDRESS=https://api.example.com
      - PUBLIC_WEB_ADDRESS=https://example.com
      - SESSION_KEY=SESSIONKEY
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
```

2. **Nginx configuration for the web service**:
```nginx
server {
    server_name example.com;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name gco.revolt.ltd;

    listen 80;
    return 404; # managed by Certbot
}
```

3. **Nginx configuration for the API service**:
```nginx
server {
    server_name api.example.com;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name example.com;

    listen 80;
    return 404; # managed by Certbot
}
```

The **web service** is running on port 3000 and is accessible directly on the host, but when accessed via nginx, I get a 502 Bad Gateway error. On the other hand, the **API service** is working fine with its nginx configuration. Could you help me resolve the issue with the web service?

**Comment by configari** [comment] 2024-12-19 19:33
I have fixed the issue, it was a proxy buffer issue.

Adding these worked:
`        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;`

**Comment by configari** [comment] 2024-12-19 19:45
Now I have new errors.
There's no way to change localhost:8000 to the custom API url and even if forced it says:
```
{
  "error": "failed to create account: attempt to write a readonly database (1032)"
}
```
For some reason.

**Comment by Southclaws** [comment] 2024-12-20 19:53
Hey @configari thanks for sharing the solution to the first issue, this will help with documentation for nginx deployments! Side question: do you think it would be helpful to provide either a Docker image with a pre-configured nginx setup? Right now the "all-on-one"/fullstack image uses the API as a proxy for the frontend which is a little unorthodox but it was a simple way to put both services inside the same container and allow users to hit it with a single endpoint without a reverse proxy. I'd love to hear your thoughts!

As for the API URL, this is configurable, my bad for not keeping up with documenting configuration variables for both backend and frontend.

If you set `NEXT_PUBLIC_API_ADDRESS` this will control where the frontend hits for API calls. It should be set to a full URL value like `http://localhost:3030`. It's present in `config.ts` in the frontend codebase, though not obvious or documented.

The full-stack image (which I believe is the default for `ghcr.io/southclaws/storyden`) should in theory work out of the box due to the aforementioned proxy behaviour, but I will need to double check this as it's been a while since I set that up and it's since only been used for one user's site that I know of.

**Comment by configari** [comment] 2024-12-21 08:58
I think it's better not to run Nginx in Docker, as it could interfere with the system's existing Nginx configurations. It would be more efficient for the user to handle the Nginx setup manually with preconfigured files that could be set up with a bash file like in [Huly Selfhosted version](https://github.com/hcengineering/huly-selfhost), rather than using Docker, because running it in Docker could disrupt the entire Nginx setup just to deploy this application.

I also tested the API URL in the Docker environment, but it still wasn't recognized and defaulted to the original API URL.

**Comment by Southclaws** [comment] 2024-12-21 12:35
Thanks for the feedback and confirming that, I'll look into the setup and try to reproduce.

**Comment by Southclaws** [comment] 2024-12-21 13:59
Okay I've figured it out, this is an annoying aspect of Next.js: environment variables are not supported, but the build process tricks you by allowing the `process.env["ENV_NAME"]` to be used then Next.js will run a text search-replace on this pattern to replace the environment variable at _build time_ so at run time there's no way to actually change this:

<img width="440" alt="image" src="https://github.com/user-attachments/assets/8da2accb-8916-40bb-9f02-1027c0f8b530" />

The "fullstack" image is designed for simple deployments with not much configuration or setup needed so it shouldn't need to be changed.

Running the container with the following command will yield a frontend+backend deployment that can be accessed in the browser at http://localhost:3000:

```
docker run -p 3000:3000 -p 8000:8000 ghcr.io/southclaws/storyden
```

(though I'm also waiting for [this build to finish](https://github.com/Southclaws/storyden/actions/runs/12445600026/job/34747084021) because I introduced an init crash in my last hastily-made PR 🫥)

But this, as you discovered will not work for a real deployment.

If you want to run a separate frontend container and backend container with a custom URL, this is a case I haven't covered yet annoyingly (mostly due to forgetting about that detail with next.js environment variables) you'll need to either:

- build your own frontend container image with NEXT_PUBLIC_API_ADDRESS set and run them both separately
- run the frontend on a separate hosting provider such as Vercel (not ideal, I know, but it lets you customise the build easily etc. and it's free to host)


Meanwhile, I'll try and figure out a solution for this, it's tough because the frontend codebase runs in the browser and thus, does not have any concept of "environment variable", effectively, everything is typically compiled-in statically once you deploy to the internet and the site is loaded in a user's browser.

One solution could be to request this information from Next.js's backend and cache it locally during startup, so the actual true backend process within Next.js (the next server.js component) _will_ have access to environment variables from the container then it can serve the configuration to the browser-side code during a first-page-load which can then cache it in local storage.

Sorry that's probably not the neatest solution you were looking for, currently I run most customer instances of Storyden either on Vercel or via a custom frontend build anyway so I've not tripped up on this until now. Thanks for reporting in detail though, I hope to get a solution out soon!

**Comment by Southclaws** [comment] 2024-12-22 16:48
Once this build completes, if you want to give it another try it should work now with the API address environment variable: https://github.com/Southclaws/storyden/actions/runs/12455942941/job/34768904359

I was able to see it work via:

```
docker run -p 3000:3000 -e NEXT_PUBLIC_API_ADDRESS=https://api.makeroom.club storyden
```

Which causes the frontend to make API calls to the endpoint of choice without a full-rebuild, this case I used the demo/community site's API at api.makeroom.club

![image](https://github.com/user-attachments/assets/478fc069-3a9f-4ac0-9371-15f25f9a5545)

**Comment by configari** [comment] 2024-12-26 16:47
The avatar issue hasn't been solved.

**Comment by Southclaws** [comment] 2024-12-27 19:42
Ah that seems to be [from Next.js](https://github.com/vercel/next.js/issues/18412) I think I forgot to use the new dynamic (real) environment variable in next-config.js for the image optimisation domain. Fix incoming.

**Comment by Southclaws** [comment] 2024-12-27 20:22
New image pushed, removed `next/image` entirely, turns out it's impossible to provide a dynamic configuration for this.

**Comment by Southclaws** [comment] 2024-12-27 20:28
also the latest build includes a proxy for the frontend, so everything lives under the same endpoint, `/api` -> API endpoints, `/` -> frontend endpoints

the `fullstack` images have this by default, though you still get port 8000 and 3000 exposed if you want to proxy these separately via nginx.

at some point I'll provide a separate frontend image too, in case people want to run backend/frontend entirely separately but not use vercel etc.

**Comment by configari** [comment] 2024-12-27 20:30
So I do not need to expose the API as another subdomain?

**Comment by Southclaws** [comment] 2024-12-27 20:35
Nope! This should work, just been testing this a bit today:

```
docker run -p 8000:8000 ghcr.io/southclaws/storyden:ghcr.io/southclaws/storyden:edge-fullstack
```

then hit `localhost:8000` and all should be working nicely.

in prod you will need to explicitly set NEXT_PUBLIC_WEB_ADDRESS & NEXT_PUBLIC_API_ADDRESS to the same address, but after that all requests will go to the same domain and hit the Go server, if the route is `/api` it handles it as an API request, otherwise it'll proxy it to the frontend.

let me know if you have any issues! this is all quite new and part of setting up a proper hosting infrastructure and docs for self-hosting, thanks for contributing!

**Comment by configari** [comment] 2024-12-27 20:56
Tried with the fullstack one on Cloudflare but having issues logging in.

**Comment by configari** [comment] 2024-12-27 21:25
Nevermind, it just started to work.

**Comment by Southclaws** [comment] 2024-12-27 21:54
is this only happening with avatars, or all images?

can you post a screenshot or text of the network tab requests to the images?

**Comment by configari** [comment] 2024-12-27 21:56
Avatars are displaying, just cannot upload a new avatar because data/avatar folder does not exist.

**Comment by Southclaws** [comment] 2024-12-27 21:57
ah, yes the folder should be auto created but it seems not, if you mount a directory into the container and create it, you should be good to go.

I'll fix the folder not auto-creating on boot for when `ASSET_STORAGE_TYPE` is set to filesystem rather than S3

**Comment by Southclaws** [comment] 2024-12-27 23:21
fixed that bug in latest build, directories are auto created - I neglected to properly test that one as my sites all use S3 (cloudflare R2) for storage rather than a local filesystem.

if all is good with the original issue, shall I close this? if you run into any more problems, feel free to open more issues! thanks again

**Closed by Southclaws** 2024-12-27 23:21 UTC
